import { useEffect, useMemo, useState } from "react";
import AppShell from "@/components/AppShell";
import PageHeader from "@/components/PageHeader";
import { Sparkles, CalendarDays, Target, ChevronDown, ChevronUp } from "lucide-react";
import { supabase } from "@/lib/supabase";

type RoadmapType = {
  id: string;
  title: string;
  goal: string;
  estimated_duration: string;
  motivation: string;
};

type RoadmapStep = {
  id: string;
  week: number;
  day: number;
  week_title: string;
  week_objective: string;
  expected_outcome: string;
  title: string;
};

export default function Roadmap() {
  const [profile, setProfile] = useState<any>(null);
  const [roadmap, setRoadmap] = useState<RoadmapType | null>(null);
  const [steps, setSteps] = useState<RoadmapStep[]>([]);
  const [expandedWeek, setExpandedWeek] = useState<number | null>(1);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadRoadmap();
  }, []);

  async function loadRoadmap() {
    setLoading(true);

    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) return;

    // Fetch Profile
    const { data: profileData } = await supabase
      .from("profiles")
      .select("*")
      .eq("id", user.id)
      .single();

    setProfile(profileData);

    // Fetch Roadmap
    const { data: roadmapData } = await supabase
      .from("roadmaps")
      .select("*")
      .eq("user_id", user.id)
      .single();

    if (roadmapData) {
      setRoadmap(roadmapData);

      // Fetch Steps
      const { data: stepsData } = await supabase
        .from("roadmap_steps")
        .select("*")
        .eq("roadmap_id", roadmapData.id)
        .order("week", { ascending: true })
        .order("day", { ascending: true });

      setSteps(stepsData || []);
    }

    setLoading(false);
  }

  const weeklyRoadmap = useMemo(() => {
    const grouped: Record<number, RoadmapStep[]> = {};

    steps.forEach((step) => {
      if (!grouped[step.week]) {
        grouped[step.week] = [];
      }

      grouped[step.week].push(step);
    });

    return grouped;
  }, [steps]);

  const totalWeeks = Object.keys(weeklyRoadmap).length;

  const totalTopics = steps.length;

  const totalDays = steps.length;

  if (loading) {
    return (
      <AppShell>
        <PageHeader
          title="Roadmap"
          subtitle="Preparing your personalized roadmap..."
        />

        <div className="px-6 py-10 text-center text-muted-foreground">
          Loading your AI roadmap...
        </div>
      </AppShell>
    );
  }

  return (
    <AppShell>
      <PageHeader
        title="Roadmap"
        subtitle="Your AI-generated learning journey."
      />
            <section className="px-6">

        <div className="glass-card bg-gradient-card p-5">

          <p className="text-xl font-semibold">
            Hello, {profile?.full_name || "Learner"} 👋
          </p>

          <p className="mt-2 text-sm text-muted-foreground">
            Here's your personalized roadmap generated by GuideMate AI.
          </p>

          <div className="mt-6">
            <div className="flex items-center gap-2 text-xs uppercase tracking-widest text-primary">
              <Sparkles className="h-3.5 w-3.5" />
              AI Roadmap
            </div>

            <h2 className="mt-2 text-xl font-bold leading-snug">
              {roadmap?.title}
            </h2>
          </div>

          {roadmap?.goal && (
            <div className="mt-6 rounded-2xl border border-border/60 bg-card p-4">
              <div className="mb-2 flex items-center gap-2 text-xs uppercase tracking-widest text-primary">
                <Target className="h-3.5 w-3.5" />
                Goal
              </div>

              <p className="text-sm leading-relaxed">
                {roadmap.goal}
              </p>
            </div>
          )}
        </div>

      </section>

      <section className="mt-6 px-6">

        <div className="grid grid-cols-3 gap-3">

          <div className="glass-card p-4 text-center">
            <p className="text-2xl font-bold">{totalWeeks}</p>
            <p className="mt-1 text-[11px] uppercase tracking-wider text-muted-foreground">
              Weeks
            </p>
          </div>

          <div className="glass-card p-4 text-center">
            <p className="text-2xl font-bold">{totalDays}</p>
            <p className="mt-1 text-[11px] uppercase tracking-wider text-muted-foreground">
              Days
            </p>
          </div>

          <div className="glass-card p-4 text-center">
            <p className="text-2xl font-bold">{totalTopics}</p>
            <p className="mt-1 text-[11px] uppercase tracking-wider text-muted-foreground">
              Topics
            </p>
          </div>

        </div>

      </section>

      <section className="mt-8 px-6">

        <h2 className="mb-4 text-sm font-semibold text-muted-foreground">
          Weekly Roadmap
        </h2>

        <div className="space-y-4">

          {Object.entries(weeklyRoadmap).map(([week, weekSteps]) => {

            const first = weekSteps[0];

            const open = expandedWeek === Number(week);

            return (

              <div
                key={week}
                className="glass-card overflow-hidden"
              >

                <button
                  onClick={() =>
                    setExpandedWeek(
                      open ? null : Number(week)
                    )
                  }
                  className="flex w-full items-center justify-between p-5 text-left"
                >

                  <div>

                    <p className="text-xs uppercase tracking-widest text-primary">
                      Week {week}
                    </p>

                    <h3 className="mt-1 text-lg font-semibold">
                      {first.week_title}
                    </h3>

                  </div>

                  {open ? (
                    <ChevronUp className="h-5 w-5 text-primary" />
                  ) : (
                    <ChevronDown className="h-5 w-5 text-muted-foreground" />
                  )}

                </button>

                {open && (

                  <div className="border-t border-border/60 px-5 py-5">

                    <div>

                      <p className="text-xs uppercase tracking-widest text-primary">
                        Objective
                      </p>

                      <p className="mt-2 text-sm leading-relaxed">
                        {first.week_objective}
                      </p>

                    </div>

                    <div className="mt-5">

                      <p className="text-xs uppercase tracking-widest text-primary">
                        Expected Outcome
                      </p>

                      <p className="mt-2 text-sm leading-relaxed">
                        {first.expected_outcome}
                      </p>

                    </div>

                  </div>

                )}

              </div>

            );

          })}

        </div>

      </section>

      <section className="mt-8 mb-10 px-6">

        <div className="glass-card p-5 text-center">

          <CalendarDays className="mx-auto mb-3 h-6 w-6 text-primary" />

          <p className="text-3xl font-bold">
            {totalTopics}
          </p>

          <p className="mt-2 text-sm text-muted-foreground">
            Total Learning Topics
          </p>

        </div>

      </section>

    </AppShell>
  );
}